_wandb:
    value:
        cli_version: 0.22.3
        e:
            n17pjztv3mcem2amalh85af3wvqdbloz:
                args:
                    - --config
                    - configs/hg-loss/adam_lr1e-1.yaml
                codePath: NLSE in PyTorch/train_xpm_unitary.py
                codePathLocal: train_xpm_unitary.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "270395555840"
                        used: "420143104"
                email: lukasskellijs@gmail.com
                executable: /home/lrk42/.conda/envs/torch-gpu/bin/python
                git:
                    commit: ae6e2ff77bdee1b90f17706dda46d3afed436a6e
                    remote: https://github.com/lukass16/LGW-Lab-NLSE.git
                gpu: NVIDIA RTX 5000 Ada Generation
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 12800
                      memoryTotal: "34351349760"
                      name: NVIDIA RTX 5000 Ada Generation
                      uuid: GPU-a90fe277-9315-0a80-865d-308b7aa692d5
                host: a1128u14n01.mghpcc.ycrc.yale.edu
                memory:
                    total: "540791115776"
                os: Linux-4.18.0-553.87.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /home/lrk42/LGW-Lab-NLSE/NLSE in PyTorch/train_xpm_unitary.py
                python: CPython 3.11.14
                root: runs/hg-phase-adam-lr1e-1
                slurm:
                    cluster_name: bouchet
                    conf: /var/lib/slurmconf/slurm.conf
                    cpus_on_node: "2"
                    cpus_per_task: "2"
                    export_env: NONE
                    get_user_env: "1"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    hint: nomultithread
                    job_account: pi_lgw23
                    job_cpus_per_node: "2"
                    job_end_time: "1775066717"
                    job_gid: "1026647"
                    job_gpus: "0"
                    job_id: "6951575"
                    job_name: xpm_train_gpu
                    job_nodelist: a1128u14n01
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1775045117"
                    job_uid: "26647"
                    job_user: lrk42
                    jobid: "6951575"
                    localid: "0"
                    mem_per_cpu: "5120"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: a1128u14n01
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /home/lrk42/LGW-Lab-NLSE/NLSE in PyTorch
                    submit_host: a1132u05n02.mghpcc.ycrc.yale.edu
                    task_pid: "2144384"
                    tasks_per_node: "1"
                    threads_per_core: "1"
                    topology_addr: hdrspine.a1128u27.a1128u14n01
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=2
                startedAt: "2026-04-01T12:05:35.553308Z"
                writerId: n17pjztv3mcem2amalh85af3wvqdbloz
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.14
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
device:
    value:
        device_id: 0
        use_cuda: true
medium:
    value:
        beta2_j: -10
        beta2_k: -10
        gamma_j: 1
        gamma_k: 1
plotting:
    value:
        mode_nr: 7
        plot_percent: 0.3
pulse:
    value:
        tau: 0.1
simulation:
    value:
        Lt: 16
        Lz: "1e-3"
        N_modes: 500
        Nt: 4096
        Nz: 200
training:
    value:
        N_train: 5000
        amplitude_downscale: "1e-1"
        batch_size: 16
        loss_fn: hg_phase
        lr: "1e-1"
        m: 8
        mask_percent: 0.8
        optimizer: adam
        transformation: identity
        w_mse: "1e4"
        w_pen: "1e3"
wandb:
    value:
        entity: lgwlab
        name: hg-phase-adam-lr1e-1
        notes: HG phase loss, Adam optimizer, lr=1e-1
        project: xpm-identity-operator
        tags:
            - hg_phase
            - identity
            - adam
            - lr1e-1
