# Analysis: Trace Loss - L-BFGS - Batch Size 2

simulation:
  Lz: 1e-3
  Nz: 200
  Lt: 16
  Nt: 4096
  N_modes: 500

medium:
  beta2_j: -10
  beta2_k: -10
  gamma_j: 1
  gamma_k: 1

pulse:
  tau: 0.1

training:
  batch_size: 2
  amplitude_downscale: 1e-1
  mask_percent: 0.8
  m: 8
  w_mse: 1e4
  w_pen: 1e3
  lr: 0.9
  N_train: 10000
  loss_fn: trace
  transformation: identity
  optimizer: lbfgs

plotting:
  plot_percent: 0.3
  mode_nr: 1

wandb:
  project: "xpm-identity-operator"
  entity: lgwlab
  name: analysis-trace-bs2
  tags: ["analysis", "trace", "identity", "lbfgs", "bs2"]
  notes: "Analysis: Trace loss, batch_size=2"

device:
  use_cuda: true
  device_id: 0
